BEGIN;

ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check;

ALTER TABLE audit_log ADD CONSTRAINT audit_log_action_check CHECK (
  action IN (
    'admin_promote_cli',
    'admin_promote_startup',
    'admin_promote_first_signin',
    'admin_role_change',
    'admin_disable_user',
    'admin_enable_user',
    'admin_delete_user',
    'admin_hard_purge_user',
    'admin_invite_issued',
    'admin_invite_revoked',
    'share_granted',
    'share_revoked',
    'share_capabilities_updated',
    'ai_connector_connected',
    'ai_connector_revoked',
    'ai_connector_expired',
    'share_token_created',
    'share_token_revoked',
    'impersonation_start',
    'impersonation_end',
    'impersonation_blocked_write',
    'session_force_logout',
    'app_config_updated',
    'admin_fx_rates_refresh',
    'fx_transfer_created',
    'fx_transfer_updated',
    'fx_transfer_reversed',
    'provider_health_rerun',
    'provider_fixer_operation',
    'instrument_undelete',
    'instrument_exclusion_toggle',
    'instrument_delisted_via_absence',
    'instrument_absence_streak_bumped',
    'instrument_absence_guard_tripped',
    'delegated_portfolio_write',
    'market_calendar_previewed',
    'market_calendar_confirmed',
    'market_calendar_invalidated',
    'market_calendar_source_updated',
    'account_created',
    'account_updated',
    'account_soft_deleted',
    'account_restored',
    'account_hard_purged',
    'quote_fallback_policy_created',
    'quote_fallback_policy_updated',
    'quote_fallback_policy_deactivated',
    'quote_fallback_manual_refresh_requested',
    'dividend_destructive_confirmed',
    'dividend_destructive_failed',
    'dividend_destructive_preview_created',
    'dividend_legacy_stock_purge_migrated',
    'dividend_calculation_confirmed',
    'dividend_calculation_reset',
    'dividend_calculation_amended',
    'dividend_stock_reconciliation_updated',
    'account_market_dividend_settings_updated'
  )
);

COMMIT;
